site_name: Helpernode v2

theme: 
    name: material
    include_homepage_in_sidebar: true
    include_search_page: false
    features:
      - navigation.sections

nav:
- Home: 'index.md'
- Using The helpernodectl CLI:
    - 'Obtaining The Binary': 'binary.md'
    - 'Shell Completion': 'shell-completion.md'
- Documentation for helpernode.yaml:
    - 'Head 2 Placeholder 1': 'h2p1.md'
    - 'Head 2 Placeholder 2': 'h2p2.md'
- Quickstarts:
    - 'Head 3 Placeholder 1': 'h3p1.md'
    - 'Head 3 Placeholder 2': 'h3p2.md'
