site_name: Helpernode v2

theme: 
    name: material
    include_homepage_in_sidebar: true
    include_search_page: false
    features:
      - navigation.sections

nav:
- Home: 'index.md'
- Using The helpernodectl CLI:
    - 'Obtaining The Binary': 'binary.md'
    - 'Shell Completion': 'shell-completion.md'
    - 'Copy Ignition Configs': 'copy-ign.md'
    - 'Get Clients': 'get-clients.md'
    - 'Install Bootstrapping': 'install-yaml.md'
    - 'Preflight Checks': 'preflight.md'
    - 'Pulling Images': 'pull.md'
    - 'Saving YAML Config': 'saving-yaml.md'
    - 'Modifying helpernodectl Behavior': 'set.md'
    - 'Starting the HelperNode Services': 'start.md'
    - 'Displaying Status': 'status.md'
    - 'Stopping the HelperNode Services': 'stop.md'
- Documentation for helpernode.yaml:
    - 'Head 2 Placeholder 1': 'h2p1.md'
    - 'Head 2 Placeholder 2': 'h2p2.md'
- Quickstarts:
    - 'Head 3 Placeholder 1': 'h3p1.md'
    - 'Head 3 Placeholder 2': 'h3p2.md'
